### ISSUE TITLE
Bug: ansi.pink should use a non-hex code 

### ISSUE THREAD

**Issue by TanklesXL** [gleam-community/ansi#11]
It is cute that the library tries to provide a pink that is close to gleam's pink, but this colour is the only one in the lib that doesnt use standard ansi escape codes and thus breaks when rendered in some terminals ( e.g. macOS terminal)

based on concensus from other gleamlins in the discord, we should use ansi colour 219

**Comment by aslilac** [comment]
looks like this was closed by #12!
